### ISSUE TITLE
Index out of range while scraping class numbers

### ISSUE THREAD

**Issue by Wolftr** [Redpandaboss09/schedule-scraper#1]
Running the executable results in this error
```
Navigated to login page...

LOGGED IN!

Finalizing values...
Scraping course names... Scraping instructor names...
Scraping class numbers...
Traceback (most recent call last):
    File "main.py", line 5, in <module>
        pdf_creator.create_schedule(data_cleaner.fix_data(scraper.caller()))
    File "scraper.py", line 169, in caller
        needed_values login(page)
    File "scraper.py", line 26, in login
        return final_joining(page)
    File "scraper.py", line 111, in final_joining
        joined = join_elements (page, course_names (page)[0], get_instructor_names(page), get_class_number(page))
    File "scraper.py", line 71, in join_elements
        joined_elements [key] [course_names[key], instructor_names[int(key[4:])], class_numbers[int(key[4:])]] 
IndexError: list index out of range
[19176] Failed to execute script 'main' due to unhandled exception!
```

**Comment by Redpandaboss09** [comment]
How many classes do you have and what are they?

**Comment by Wolftr** [comment]
8 Classes. In order:
Calculus
Computer Science A
Computer Aided Design and 3D Printing
English
Ethics
Computer Science Principles
Introduction to Cybersecurity

**Comment by Redpandaboss09** [comment]
I'll try a fix this weekend then

**Comment by Redpandaboss09** [comment]
Try the new release, report on issues if another error
